/**
 * Reference catalog of Windows commands spanning MS-DOS, 9x, NT, 2000, XP,
 * Vista, 7, 8, 10, and 11 (CMD internal + external utilities, plus a few common
 * PowerShell cmdlets). Used by the builder's searchable command reference.
 *
 * Descriptions are written with plenty of plain-language keywords so the search
 * can match a single word or a whole sentence (for example "show my ip address"
 * finds `ipconfig`).
 */

export type WindowsCommand = {
  name: string;
  category: string;
  description: string;
};

export const WINDOWS_COMMANDS: WindowsCommand[] = [
  // ----- Files & folders -----
  { name: "dir", category: "Files & folders", description: "List files and folders in a directory. Show contents of a folder, view file names, sizes, and dates." },
  { name: "cd", category: "Files & folders", description: "Change the current directory or folder. Move to another location. Also called chdir." },
  { name: "chdir", category: "Files & folders", description: "Change or display the current directory. Same as cd." },
  { name: "md", category: "Files & folders", description: "Make a new directory or folder. Create a folder. Also called mkdir." },
  { name: "mkdir", category: "Files & folders", description: "Create a new folder or directory, including nested paths." },
  { name: "rd", category: "Files & folders", description: "Remove or delete an empty directory or folder. Also called rmdir." },
  { name: "rmdir", category: "Files & folders", description: "Delete a folder or directory. Use /s to remove a folder and everything inside it." },
  { name: "del", category: "Files & folders", description: "Delete one or more files. Remove files. Also called erase." },
  { name: "erase", category: "Files & folders", description: "Delete or remove files. Same as del." },
  { name: "copy", category: "Files & folders", description: "Copy one or more files to another location. Duplicate a file." },
  { name: "xcopy", category: "Files & folders", description: "Copy files and whole directory trees, including subfolders. Powerful copy with many options." },
  { name: "robocopy", category: "Files & folders", description: "Robust file copy for mirroring folders, backups, and network transfers with retry and resume. Replaces xcopy on modern Windows." },
  { name: "move", category: "Files & folders", description: "Move files or rename a folder. Relocate a file to another directory." },
  { name: "ren", category: "Files & folders", description: "Rename a file or folder. Change a file name. Also called rename." },
  { name: "rename", category: "Files & folders", description: "Rename files or folders. Same as ren." },
  { name: "type", category: "Files & folders", description: "Display the contents of a text file on screen. Print or read a file to the console." },
  { name: "more", category: "Files & folders", description: "Display output one screen at a time. Page through long text or file contents." },
  { name: "attrib", category: "Files & folders", description: "Display or change file attributes such as read-only, hidden, system, and archive." },
  { name: "tree", category: "Files & folders", description: "Display the folder structure of a drive or path as a graphical tree." },
  { name: "fc", category: "Files & folders", description: "Compare two files and show the differences between them." },
  { name: "comp", category: "Files & folders", description: "Compare the contents of two files or sets of files byte by byte." },
  { name: "where", category: "Files & folders", description: "Find and locate the path of a program or file, like which on Linux." },
  { name: "mklink", category: "Files & folders", description: "Create a symbolic link, hard link, or directory junction between files or folders." },
  { name: "fsutil", category: "Files & folders", description: "File system utility to manage NTFS, hard links, sparse files, quotas, and volume info." },
  { name: "compact", category: "Files & folders", description: "Display or change NTFS compression on files and folders to save disk space." },
  { name: "cipher", category: "Files & folders", description: "Display or change encryption (EFS) on NTFS files and folders, or securely wipe free space." },
  { name: "expand", category: "Files & folders", description: "Extract or expand compressed files from cabinet (.cab) archives." },
  { name: "tar", category: "Files & folders", description: "Create or extract .tar and .tar.gz archives. Built into Windows 10 and 11." },
  { name: "curl", category: "Files & folders", description: "Transfer data from or to a server and download files over HTTP, HTTPS, and FTP. Built into Windows 10 and 11." },
  { name: "print", category: "Files & folders", description: "Send a text file to a printer." },
  { name: "recover", category: "Files & folders", description: "Recover readable data from a bad or defective disk." },
  { name: "replace", category: "Files & folders", description: "Replace files in a destination folder with files of the same name from a source." },
  { name: "subst", category: "Files & folders", description: "Map a folder path to a virtual drive letter." },
  { name: "assoc", category: "Files & folders", description: "Display or change file extension associations, for example which program opens .txt files." },
  { name: "ftype", category: "Files & folders", description: "Display or change the program used to open a given file type." },
  { name: "openfiles", category: "Files & folders", description: "List or disconnect files opened by remote users over a network share." },

  // ----- Disks & volumes -----
  { name: "diskpart", category: "Disks & volumes", description: "Manage disks, partitions, and volumes. Create, delete, format, extend, and assign drive letters." },
  { name: "format", category: "Disks & volumes", description: "Format a disk or drive for use, erasing all data on it." },
  { name: "chkdsk", category: "Disks & volumes", description: "Check a disk for errors and bad sectors, and fix file system problems." },
  { name: "chkntfs", category: "Disks & volumes", description: "Display or change whether disk checking runs automatically at boot." },
  { name: "defrag", category: "Disks & volumes", description: "Defragment and optimize a hard drive to improve performance." },
  { name: "label", category: "Disks & volumes", description: "Create, change, or delete the volume label (name) of a disk." },
  { name: "vol", category: "Disks & volumes", description: "Display the disk volume label and serial number." },
  { name: "diskperf", category: "Disks & volumes", description: "Enable or disable disk performance counters." },
  { name: "mountvol", category: "Disks & volumes", description: "Create, delete, or list volume mount points." },
  { name: "convert", category: "Disks & volumes", description: "Convert a FAT or FAT32 volume to NTFS without losing data." },

  // ----- Networking -----
  { name: "ipconfig", category: "Networking", description: "Show your IP address and network configuration. Display, release, and renew TCP/IP settings, DNS, and MAC address." },
  { name: "ping", category: "Networking", description: "Test network connectivity to a host or website. Check if a server is reachable and measure latency." },
  { name: "tracert", category: "Networking", description: "Trace the route packets take to reach a host and show each hop along the way." },
  { name: "pathping", category: "Networking", description: "Combine ping and tracert to trace a route and report packet loss at each hop." },
  { name: "netstat", category: "Networking", description: "Display active network connections, listening ports, and network statistics." },
  { name: "nslookup", category: "Networking", description: "Query DNS to look up the IP address of a domain name or troubleshoot DNS problems." },
  { name: "netsh", category: "Networking", description: "Network shell to configure interfaces, Wi-Fi, firewall, IP, proxy, and reset the network stack." },
  { name: "net", category: "Networking", description: "Manage network resources, shares, users, drives, and services. net use, net user, net share, net start." },
  { name: "arp", category: "Networking", description: "Display or modify the ARP cache that maps IP addresses to physical MAC addresses." },
  { name: "route", category: "Networking", description: "Display or change the IP routing table." },
  { name: "getmac", category: "Networking", description: "Display the MAC (physical) address of network adapters." },
  { name: "hostname", category: "Networking", description: "Display the name of the current computer." },
  { name: "nbtstat", category: "Networking", description: "Show NetBIOS over TCP/IP statistics and name tables for troubleshooting." },
  { name: "ftp", category: "Networking", description: "Transfer files to and from an FTP server from the command line." },
  { name: "tftp", category: "Networking", description: "Transfer files using the Trivial File Transfer Protocol." },
  { name: "telnet", category: "Networking", description: "Connect to a remote host or test if a TCP port is open. Optional Windows feature." },
  { name: "wget", category: "Networking", description: "Download files from the web (PowerShell alias for Invoke-WebRequest)." },

  // ----- System & information -----
  { name: "systeminfo", category: "System & information", description: "Display detailed system configuration, OS version, hardware, memory, and installed hotfixes." },
  { name: "ver", category: "System & information", description: "Display the Windows version number." },
  { name: "set", category: "System & information", description: "Display, set, or remove environment variables for the current session." },
  { name: "setx", category: "System & information", description: "Set environment variables permanently for the user or the whole machine, or from a script." },
  { name: "path", category: "System & information", description: "Display or set the search path for executable files (the PATH variable)." },
  { name: "date", category: "System & information", description: "Display or set the system date." },
  { name: "time", category: "System & information", description: "Display or set the system time." },
  { name: "tzutil", category: "System & information", description: "Display or set the Windows time zone." },
  { name: "w32tm", category: "System & information", description: "Configure and check Windows Time service and synchronize the clock." },
  { name: "wmic", category: "System & information", description: "Windows Management Instrumentation command line to query hardware, software, and OS details (deprecated but widely used)." },
  { name: "powercfg", category: "System & information", description: "Configure power settings, sleep, hibernate, and generate battery and energy reports." },
  { name: "bcdedit", category: "System & information", description: "Edit the Boot Configuration Data store that controls how Windows boots." },
  { name: "reg", category: "System & information", description: "Read, add, delete, export, and import Windows registry keys and values from the command line." },
  { name: "regedit", category: "System & information", description: "Open the Registry Editor to view and change the Windows registry." },
  { name: "gpupdate", category: "System & information", description: "Refresh local and Active Directory Group Policy settings immediately." },
  { name: "gpresult", category: "System & information", description: "Display the Resultant Set of Policy (RSoP) applied to a user or computer." },
  { name: "sfc", category: "System & information", description: "System File Checker scans and repairs corrupted or missing Windows system files." },
  { name: "dism", category: "System & information", description: "Deployment Image Servicing and Management to repair Windows, manage features, drivers, and images." },
  { name: "slmgr", category: "System & information", description: "Software Licensing Management to activate Windows, view license status, and manage product keys." },
  { name: "winver", category: "System & information", description: "Show the Windows version and build in a dialog box." },
  { name: "msinfo32", category: "System & information", description: "Open System Information with a detailed hardware and software report." },
  { name: "verifier", category: "System & information", description: "Driver Verifier to stress test and detect faulty drivers." },
  { name: "driverquery", category: "System & information", description: "List installed device drivers and their properties." },
  { name: "pnputil", category: "System & information", description: "Add, delete, and list device drivers in the driver store." },

  // ----- Processes & performance -----
  { name: "tasklist", category: "Processes & performance", description: "List all running processes, their process IDs (PID), and memory usage." },
  { name: "taskkill", category: "Processes & performance", description: "End or kill a running process by name or process ID (PID)." },
  { name: "start", category: "Processes & performance", description: "Open a program, file, folder, or URL in a new window or process." },
  { name: "wmic process", category: "Processes & performance", description: "Query or terminate processes with detailed information via WMIC." },
  { name: "schtasks", category: "Processes & performance", description: "Create, delete, run, and manage scheduled tasks. Automate programs to run at a time or event." },
  { name: "at", category: "Processes & performance", description: "Schedule commands to run at a specific time (legacy, replaced by schtasks)." },
  { name: "typeperf", category: "Processes & performance", description: "Display or log performance counter data in real time." },
  { name: "logman", category: "Processes & performance", description: "Create and manage performance counter and event trace log sessions." },
  { name: "tracerpt", category: "Processes & performance", description: "Process event trace logs and generate reports." },

  // ----- Services -----
  { name: "sc", category: "Services", description: "Service Control to create, start, stop, query, and configure Windows services." },
  { name: "net start", category: "Services", description: "Start a Windows service by name." },
  { name: "net stop", category: "Services", description: "Stop a running Windows service by name." },
  { name: "services.msc", category: "Services", description: "Open the Services management console to manage Windows services." },

  // ----- Users & security -----
  { name: "net user", category: "Users & security", description: "Create, delete, and manage local user accounts and reset passwords." },
  { name: "net localgroup", category: "Users & security", description: "Add or remove users from local groups such as Administrators." },
  { name: "whoami", category: "Users & security", description: "Display the current user name, groups, and privileges." },
  { name: "runas", category: "Users & security", description: "Run a program as another user, for example as an administrator." },
  { name: "cacls", category: "Users & security", description: "Display or edit file access control lists (permissions). Legacy, replaced by icacls." },
  { name: "icacls", category: "Users & security", description: "Display, grant, deny, and reset file and folder permissions (access control lists)." },
  { name: "takeown", category: "Users & security", description: "Take ownership of a file or folder so you can change its permissions." },
  { name: "gpedit.msc", category: "Users & security", description: "Open the Local Group Policy Editor." },
  { name: "secedit", category: "Users & security", description: "Analyze and apply security policy templates." },
  { name: "auditpol", category: "Users & security", description: "Display and configure audit policy settings." },

  // ----- Batch & scripting -----
  { name: "echo", category: "Batch & scripting", description: "Display a message or turn command echoing on or off. Print text to the console." },
  { name: "rem", category: "Batch & scripting", description: "Add a comment or remark in a batch file. Ignored when the script runs." },
  { name: "pause", category: "Batch & scripting", description: "Pause the batch file and wait for the user to press any key." },
  { name: "call", category: "Batch & scripting", description: "Call another batch file or a label from within a batch file." },
  { name: "goto", category: "Batch & scripting", description: "Jump to a labeled line in a batch file." },
  { name: "if", category: "Batch & scripting", description: "Perform conditional branching in a batch file based on a test." },
  { name: "for", category: "Batch & scripting", description: "Loop over files, folders, numbers, or text in a batch file." },
  { name: "setlocal", category: "Batch & scripting", description: "Begin localization of environment changes in a batch file." },
  { name: "endlocal", category: "Batch & scripting", description: "End localization of environment changes in a batch file." },
  { name: "shift", category: "Batch & scripting", description: "Shift the position of batch file parameters (%1, %2, ...)." },
  { name: "exit", category: "Batch & scripting", description: "Exit the command interpreter or a batch script, optionally with an exit code." },
  { name: "choice", category: "Batch & scripting", description: "Prompt the user to choose one option from a list of keys in a batch file." },
  { name: "timeout", category: "Batch & scripting", description: "Wait for a set number of seconds, optionally letting the user skip the wait." },
  { name: "waitfor", category: "Batch & scripting", description: "Wait for or send a signal across the network to synchronize scripts." },
  { name: "cmd", category: "Batch & scripting", description: "Start a new instance of the Windows command interpreter." },
  { name: "command", category: "Batch & scripting", description: "Start the legacy MS-DOS command interpreter (16-bit)." },
  { name: "powershell", category: "Batch & scripting", description: "Launch Windows PowerShell to run cmdlets and scripts." },
  { name: "pwsh", category: "Batch & scripting", description: "Launch PowerShell 7+ (cross-platform PowerShell Core)." },
  { name: "wscript", category: "Batch & scripting", description: "Run a Windows Script Host script (VBScript or JScript) with a GUI." },
  { name: "cscript", category: "Batch & scripting", description: "Run a Windows Script Host script from the console." },
  { name: "title", category: "Batch & scripting", description: "Set the title of the command prompt window." },
  { name: "color", category: "Batch & scripting", description: "Change the background and text color of the console." },
  { name: "prompt", category: "Batch & scripting", description: "Change the command prompt text." },
  { name: "cls", category: "Batch & scripting", description: "Clear the console screen." },
  { name: "pushd", category: "Batch & scripting", description: "Save the current directory and change to a new one, including network paths." },
  { name: "popd", category: "Batch & scripting", description: "Return to the directory saved by pushd." },
  { name: "verify", category: "Batch & scripting", description: "Turn on or off verification that files are written correctly to disk." },
  { name: "break", category: "Batch & scripting", description: "Set or clear extended Ctrl+C checking (legacy)." },

  // ----- Text & filters -----
  { name: "find", category: "Text & filters", description: "Search for a text string in a file or command output." },
  { name: "findstr", category: "Text & filters", description: "Search files for text using patterns and regular expressions. Grep for Windows." },
  { name: "sort", category: "Text & filters", description: "Sort lines of text alphabetically or numerically." },
  { name: "clip", category: "Text & filters", description: "Copy command output to the Windows clipboard." },

  // ----- Shutdown & power -----
  { name: "shutdown", category: "Shutdown & power", description: "Shut down, restart, log off, or hibernate the computer, optionally after a delay." },
  { name: "logoff", category: "Shutdown & power", description: "Log off the current user session." },
  { name: "rundll32", category: "Shutdown & power", description: "Run functions stored in DLL files, such as locking the workstation or opening control panels." },

  // ----- Misc & tools -----
  { name: "help", category: "Misc & tools", description: "Show help information for Windows commands." },
  { name: "doskey", category: "Misc & tools", description: "Create command macros and recall command history." },
  { name: "mode", category: "Misc & tools", description: "Configure system devices such as the console size, COM, and LPT ports." },
  { name: "chcp", category: "Misc & tools", description: "Display or change the active console code page (character set)." },
  { name: "calc", category: "Misc & tools", description: "Open the Windows Calculator." },
  { name: "notepad", category: "Misc & tools", description: "Open the Notepad text editor, optionally with a file." },
  { name: "explorer", category: "Misc & tools", description: "Open File Explorer at a folder or launch the shell." },
  { name: "control", category: "Misc & tools", description: "Open the Control Panel or a specific control panel applet." },
  { name: "mstsc", category: "Misc & tools", description: "Open Remote Desktop Connection to connect to another computer." },
  { name: "eventvwr", category: "Misc & tools", description: "Open Event Viewer to inspect system, application, and security logs." },
  { name: "wevtutil", category: "Misc & tools", description: "Query, export, and clear Windows event logs from the command line." },
  { name: "taskmgr", category: "Misc & tools", description: "Open Task Manager to view and manage running apps and processes." },
  { name: "msconfig", category: "Misc & tools", description: "Open System Configuration to manage startup and boot options." },
  { name: "cleanmgr", category: "Misc & tools", description: "Open Disk Cleanup to free space by removing temporary files." },
  { name: "winget", category: "Misc & tools", description: "Windows Package Manager to search, install, upgrade, and remove apps. Windows 10 and 11." },
  { name: "wsl", category: "Misc & tools", description: "Windows Subsystem for Linux to run Linux distributions and commands." },
  { name: "wt", category: "Misc & tools", description: "Launch Windows Terminal, optionally with tabs and profiles." },
  { name: "bitsadmin", category: "Misc & tools", description: "Create and manage background file transfer jobs (legacy, replaced by PowerShell BITS cmdlets)." },
  { name: "certutil", category: "Misc & tools", description: "Manage certificates, verify hashes, and encode or decode files." },
  { name: "fondue", category: "Misc & tools", description: "Enable optional Windows features on demand." }
];
